= TODO

* [ ] Create "self" or "config" group.
** [ ] Command "enable-completion" to auto-generate the necessary autocomplete stuff according to directions at https://click.palletsprojects.com/en/8.1.x/shell-completion/#enabling-completion.
** [ ] Command "check-dependencies" to check whether the necessary system packages for carbide are present (e.g. the `code` command).
* [ ] Command to get you in the state for PR review w/ a specified repo and branch.
* [ ] Command to go to a registered dir.
* [ ] Command to register a specified .py argparse script for running thru this CLI.
* [ ] Command to make a TOML-based acronym file. Possibly convert it to Asciidoc too.
** [ ] This could be its own package.
*** [ ] Then allow `carbide` to manage public/private acronyms for you, publishing new ones to the correct place. Would want to make it "feel" different when you're publishing to public, as opposed to private, so there are less human mistakes. This could take the form of an extra confirmation prompt for publishing to public. ("Publishing" here could refer to adding the acronym to the database in the first place, or perhaps pushing to Git.)
*** [ ] Said package might allow output format configuration. Just list acronyms, or also meanings? Even also descriptions? Output in one large block of text, or on separate lines?
* [ ] Command to help create estimation tables. Would be nice to be able to sum hour estimates by row and column. Could be AsciiDoc!
* [ ] Command to take me to the specified section of a specified/registered repo.
** [ ] Allow overwriting registered git repos, e.g. if it is relocated on the system.
* [ ] Command using `nmap` to map desktop network topology.
** [ ] Command to set IP addresses of desktop devices according to a configured/registered map (could add to `register` group).
* [ ] Would be nice to integrate some sort of TODO tracking on a large scale (like a TODO list you might keep on your whiteboard).
* [ ] Command to go through a full firmware build + deploy + reboot.
** [ ] `notify-send` when it's done.
*** [ ] Sugar: Have a logo for carbide to put with the notify-send.
* [ ] Make sure users can easily plumb their own Click commands into the system.
** [ ] Test
** [ ] Document
* [ ] Command for registering Outlook PWA for notify-sends of calendar events. Unfortunately Outlook PWA doesn't work in this regard.
* [ ] Command for listing/pushing any non-pushed commits in any of your Git repos.
* [ ] Add global cspell dictionary management.
* [ ] Streamline: `watch -n 300 'echo $(date && git pull 2>&1 | tail -n 1) >> /tmp/git-pull-watchlog.log && cat /tmp/git-pull-watchlog.log | tail'`
** Ref. https://askubuntu.com/questions/501017/gnu-watch-without-erasing-previous-outputs/1512631#1512631
** Would want to auto-allocate a file in `/tmp` using a GUID or similar.
* [ ] Command for using https://github.com/eradman/entr[`entr`] (you can APT-install it)
